'###SPEEDTEST® CLI][
'
'][Internet connection measurement][ 
'for developers
'Speedtest CLI brings the trusted technology
'and global server network behind Speedtest to the command line.
'Built for software developers, 
'system administrators 
'and computer enthusiasts alike, 
' Speedtest CLI
'is the first official 
'Linux-native 
'Speedtest application backed
'by Ookla®.
'>
'][>With<][
'>
']['# Speedtest CLI, you can easily:][
'  
'Measure internet connection performance metrics like download, upload, latency 
'and packet loss natively without relying on a web browser
'Test the internet connection of your Linux desktop, a remote server
'or even lower-powered devices such 
'as the Raspberry Pi® 
'with the Speedtest Server Network™
'Set up automated scripts to collect connection performance data, including trends over time
'Use Speedtest
'in your programs by wrapping it 
'in the programming language of your choice
'View test results via CSV, JSONL 
'or JSON
'>
'Install Options
'macOSUbuntu/DebianFedora/Centos/RedhatFreeBSD
'>
'brew tap teamookla/speedtest
'brew update
'Example how to remove conflicting or old versions using brew
'# brew uninstall speedtest --force
'brew install speedtest --force
'Download Speedtest CLI
'Speedtest CLI is maintained by the Ookla team. For assistance, please direct all inquiries to support@ookla.com.
'>
'macOS
'Download for macOS
'>
'Installing via brew will ensure you are always running the most up-to-date version of Speedtest CLI. You should update brew as frequently as possible.
'>
'Windows
'Download for Windows
'>
'Available for x86_64 only.
'>
'Linux
'Download for Linux   
'>
'Available for: i386, x86_64, arm32, arm32hf, and arm64.
'>
'
'
'FreeBSD
'Download for FreeBSD
'>
'Available for x86_64 only.
